spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/team?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: sfs2023@163.com
    password: FWLMRECEDQGFJCFN
    default-encoding: utf-8
    properties:
      mail:
        debug: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

manager:
  email: root@root.root
  password: root

server:
  port: 8080
